services:
  backend:
    image: ${ECR_REGISTRY}/chess-backend:${IMAGE_TAG}
    restart: always
    ports:
      - '3000:3000'
    env_file: /opt/chessverse/.env

  ws:
    image: ${ECR_REGISTRY}/chess-ws:${IMAGE_TAG}
    restart: always
    ports:
      - '8080:8080'
    env_file: /opt/chessverse/.env
